io:
  curity:
    oauth2:
      issuer: https://login-external.curity.local/external/~
      clientId: jwt-assertion-test-client
      clientSecret: 6sND1PNej4ah58PRQFq18xlElfxgNTIuHojYf8mLNgjfPa5DRk9P5fTQjSiBJypg
      grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
      jwt:
        keystore-path: src/main/resources/demo-client.p12
        keystore-password: Secr3t
        key-alias: demo-client
spring:
  main:
    web-application-type: none
